# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'password'
  redis: '6TFRVm6XZey6BrUAt-kCcEbBGDyrWUCX'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: '3O35fx4RWIYM3QLn8iDYlzXLMRv6bkGx'

  emailSecretHashPepper: 'cFjyHNKcZNhgqylQYoVvFu2smGPOzWWB'
  jwtHmacSha512PrivateKey: 'jE71XpNGj8b3sl6UV0H9_C3fSioeVy-w'
  jwtRefreshTokenHashPepper: '1bPcIWTYyZdfvN5QJc08104-hJse1RkD'
  # serverSideSessionKeyHashPepper: 'vjlQjjfQOwwe8Xn3gRDQVHvd41HZgs0Q'

test:
  database: 'C6740du8MqMl5uDTWZyLmrTUO-ojyxj_'
  redis: 'Bh6SIcrq3u-kdYgKfbY0Q1BzOjQ6pK18'

  emailSecretHashPepper: 'awQamdlCLLpKtzfNJAdSFrBCbOexZFQV'
  jwtHmacSha512PrivateKey: 'PvLoRQGbSpt55t_88FZfxxdf1Ek87d4c'
  jwtRefreshTokenHashPepper: 'hPndLrfQaE4RSyaEJ9eu8zIT05-4kW_t'
  # serverSideSessionKeyHashPepper: 'u_olsaFZg-4_iwY9S3sgOY_p4qAidIC1'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'tXynEaendsaAjs_2FEoVa5Ob5p4NNQd9'
  serviceSecret: 's3p-mqjcyVK32ZFIT72k_Ju1p9yyUDdP'

  emailSecretHashPepper: 'XqDHpLMkyOITC0yGjrHm-LgqGZZ_vuEr'
  jwtHmacSha512PrivateKey: 'wmZ6GTKHtXykZ0r4TvxhGf1hKcQIz39s'
  jwtRefreshTokenHashPepper: 'kZVpf3Y_Kv7t6HoFxK6skJMctQWvlkzl'
  # serverSideSessionKeyHashPepper: 'EuQCWgsYqApc8c6Pr0P9EM1QFJ2LlOqE'

# Passwords used in production mode.
production:
  database: 'MvgvFSg7grUsKlh_qxdwRKswnrQWmh9i'
  serviceSecret: 'nMVqBmOasmeYCYtEae-qxbeXYTpdeVGy'

  emailSecretHashPepper: 'wEJZ-OhJ3JksEUWOT6gn2qXcaU3e_1g_'
  jwtHmacSha512PrivateKey: 'SNSRLqcmGX52AB3t7_ml5cLr4WqPCtqr'
  jwtRefreshTokenHashPepper: 'y8NbBuE5faa_rotzstF68uvL7xHhf9ha'
  # serverSideSessionKeyHashPepper: 'm0S-EW-8TaVmCI0NfpiMnMvse88o9SOK'
